### ISSUE TITLE
Custom Template {{#if blogReady}} not working

### ISSUE THREAD

**Issue by maurop123** [meteor-blog/meteor-blog#227]
I've added ryw:blog to my app and tried to using the completely custom templates from the getting started example...
```
<template name="myBlogIndexTemplate">
  <h1>Welcome to my Blog</h1>
  <ul>
    {{#if blogReady}}
      {{#each posts}}
        <li>
          <h2>{{title}}</h2>
          <p>Published on {{publishedAt}}</p>
          <p>Excerpt: {{excerpt}}</p>
        </li>
      {{else}}
        <li>No posts found.</li>
      {{/each}}
    {{else}}
      <li>Loading...</li>
    {{/if}}
  </ul>
</template>
```
... but it doesn't change from  "Loading..." [Live Demo](http://about.leadmiami.co/blog)

[GitHub Link](https://github.com/MptySquare/LEADMiami) Is there a step I'm missing?

**Comment by william-bratches** [comment]
+1

**Comment by hellogerard** [comment]
@maurop123 I ran your repo and noticed that it was on Meteor 1.1. The latest Meteor Blog is only compatible with Meteor 1.2. I ran `meteor update` on your repo and it appeared to fix your issue.

@william-bratches What version of Meteor are you using?
