### ISSUE TITLE
There is no route for the path: /blog

### ISSUE THREAD

**Issue by achtan** [meteor-blog/meteor-blog#228]
Hi, i am getting error `There is no route for the path: /blog`
my packages are:

``````
standard-minifiers
meteor-base
mobile-experience
mongo
blaze-html-templates
session
jquery
tracker
logging
reload
random
ejson
spacebars
check

# languages
grigio:babel
flemay:less-autoprefixer
react


# security
accounts-ui
accounts-password
# accounts-facebook
ongoworks:security
alanning:roles
#browser-policy

# router
kadira:flow-router
kadira:react-layout
kadira:blaze-layout
useraccounts:flow-routing


# collections
dburles:collection-helpers
aldeed:simple-schema
aldeed:collection2
matb33:collection-hooks
reywood:publish-composite
tmeasday:publish-counts
percolate:migrations

# lib
reactive-var
reactive-dict
mrt:reactive-object
frozeman:template-var
meteorhacks:ssr
msavin:fetcher
percolate:paginated-subscription
email
jparker:crypto-md5
cfs:standard-packages
cfs:gridfs
cfs:filesystem
cfs:graphicsmagick
momentjs:moment

# serach
meteorhacks:search-source

# helpers
service-configuration
underscore
underscorestring:underscore.string
digilord:faker

# devel
msavin:mongol
msavin:jetsetter


# design
cwaring:modernizr
fortawesome:fontawesome
semantic:ui
useraccounts:semantic-ui
fabienb4:autoform-semantic-ui

# plugins
natestrauser:select2
mizzao:autocomplete
juliancwirko:s-alert
juliancwirko:s-alert-slide
miro:mailchimp
miro:mailchimp-lists
natestrauser:jquery-scrollto
# okgrow:analytics
aldeed:autoform
ryw:blog

# SEO
spiderable
# gadicohen:sitemaps
kadira:dochead

# dev
#meteorhacks:kadira
#kadira:debug
``````
any ides ?

**Comment by hellogerard** [comment]
I have a feeling there might be a conflict with other route-related packages such as `useraccounts`. Can you try this: remove packages one-by-one and see if the the `/blog` route ever comes up?

**Comment by step21** [comment]
I have a similar problem, but maybe weirder. The error message is "Oops, looks like there's no route on the client or the server for url: "." There was a catchall route such as "Router.route('/.*)', " for 404s, and with that there was a conflict detected, without just the block package gives an error on the page.

**Comment by step21** [comment]
@hellogerard No, I did not mean that, there are other packages installed, such as iron router. Do you want a list? And, sorry for not mentioning this, but /blog actually works (except no content, just "This blog looks empty") but /blog/admin does not. And not sure why. There is a user logged in which I could confirm by running Meteor.user in the console of the browser.

**Comment by chriswessels** [comment]
+1.

But to be specific, if the app is requested with one of the in-app routes, it loads fine. However, if it is requested with a blog route, like `/blog`, I get the following logged to the console:

    There is no route for the path: /admin/blog

If the blog route is navigated to AFTER the app has loaded, I have no problems.

I'm using `flow-router` and `blaze-layout`.

**Comment by onedr0p** [comment]
+1 Not sure why this is happening @chriswessels maybe this package was built with iron router in mind?

In any case it's happening to me. I manually insert a blog post and it doesn't even look like I'm subscribed to a publication. Meaning, meteortoys shows nothing in the blog_posts collection.

**Comment by hellogerard** [comment]
Having trouble replicating. Can one of you guys create a repo that consistently reproduces this issue?

**Comment by shyal** [comment]
+1 does not work with FlowRouter

**Comment by shyal** [comment]
OK I think this bug belongs more to the [example blog repo](https://github.com/meteor-blog/example-blog-app) than this one, as even that repo does not work with FlowRouter when following instructions.

Make sure you define:

```
FlowRouter.route('/', {
  action: function() {
    BlazeLayout.render('layout', {
    	main: "home"
    });
  }
});
```

and a layout file:

```
<head>
    <meta charset="UTF-8">
    <title>Meteor Blog Example</title>
    <link rel="alternate" type="application/rss+xml" title="Example Blog App" href="/rss/posts">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<template name="layout">
    <div class="header">
        {{> header}}
    </div>
    <div class="container">
        {{> Template.dynamic template=main}}
    </div>
    <div class="footer">
        {{> footer}}
    </div>
</template>
```

Then it works.

**Comment by shyal** [comment]
I've also noticed things start breaking when I convert blog.js to blog.coffee.

**Comment by khaigh** [comment]
I believe the issue when using FlowRouter is that FlowRouter (by default) gets initialized during a Meteor.startup and attempts to route the request before the /admin/blog and /blog routes are added during its Meteor.startup (see router.coffee). You can fix this by calling FlowRouter.wait().
[https://github.com/meteorhacks/flow-router#flowrouterwait-and-flowrouterinitialize](https://github.com/meteorhacks/flow-router#flowrouterwait-and-flowrouterinitialize)

Adding the following client code will address the issue:
```
FlowRouter.wait();
Meteor.startup(function() {
  FlowRouter.initialize();
});
```

**Comment by nilsi** [comment]
Hey guys,

Im also having this problem with Flow Router. Where am I supposed to add that code @khaigh. I tried adding add the start of my routes.js but it did not work.

@shyal I defined it like your example. What exactly in your code should make it work?

Thanks for the help.

**Comment by hellogerard** [comment]
Much thanks to @khaigh.
