### ISSUE TITLE
Edit button remains visible on logout

### ISSUE THREAD

**Issue by VesterDe** [meteor-blog/meteor-blog#229]
As the issue says, if you're Admin and can edit posts, the edit button is visible next to author meta bellow the title. Logging out doesn't remove the button. The button redirects to /blog on click.

In case it's only me, possibly relevant packages are:
alanning:roles
zimme:active-route
accounts-password

**Comment by hellogerard** [comment]
I can't seem to replicate the problem. In fact, it looks fine on the Meteor Blog example (e.g. http://blog-example.meteor.com/blog/dette-er-en-test). Can you try removing the packages in your app one-by-one and see if it goes away?

**Comment by hellogerard** [comment]
I'll reopen if this is an issue.
