### ISSUE TITLE
Hazy image

### ISSUE THREAD

**Issue by gregorygilles** [meteor-blog/meteor-blog#230]
This is an screenshot taken of a blog I am making:

<img width="604" alt="screen shot 2015-11-17 at 5 52 51 pm" src="https://cloud.githubusercontent.com/assets/6465766/11227460/13f8486a-8d54-11e5-9939-797f7af2ebe3.png">

As you can tell, half of the image is coming off hazy. Is there any explanation for this?

Thanks!

**Comment by hellogerard** [comment]
I can't imagine this is blog related. There's no post-processing of images (in fact, resizing of images should be on the roadmap), and any modifications during display is achieved thru CSS.

**Comment by hellogerard** [comment]
Dupe of #247.
