### ISSUE TITLE
No language support for the `load more` button text.

### ISSUE THREAD

**Issue by zhaoyao91** [meteor-blog/meteor-blog#232]
I want to translate the text of the `load more` button, but I can't find any language support for it.

**Comment by hellogerard** [comment]
That would make a great pull request :-)

It should be pretty easy to follow the example of the other language strings already supported.

**Comment by thoragio** [comment]
I've created a pull request for this change after testing it.

**Comment by hellogerard** [comment]
Closed by #246.
