### ISSUE TITLE
Tags being saved as String when empty

### ISSUE THREAD

**Issue by fgarci03** [meteor-blog/meteor-blog#235]
When no tags are provided while creating a post, it stores them as an empty string instead of an empty array.

I ran into problems while trying to $unwind the tags field and noticed that.

The problem actually seems to be with typeahead, but it's not a typeahead bug per-se.
What do you think?

**Comment by hellogerard** [comment]
Sounds right. Could be a very simple and straightforward PR. Care to take a shot at a PR?

**Comment by fgarci03** [comment]
Done: https://github.com/meteor-blog/meteor-blog/pull/241

Please review the change.
My first time doing Coffee. Don't hit me pls =D
