### ISSUE TITLE
Sort posts by date

### ISSUE THREAD

**Issue by olumytee** [meteor-blog/meteor-blog#236]
Hi, sorry for the newbie question but how do I sort the posts by date making sure the most recent post is on top ? I am using a custom template. Thank you.

<div class="container ">
        {{#if blogReady}} {{#each posts}}
        <div class="card hoverable">
                <div class="card-content">
                        <h6 class="card-title">{{title}}</h6>
                        <p class="truncate">{{excerpt}}</p>
                </div>
                <div class="card-action">
                        <a href="/blog/{{slug}}">FULL POST</a>
                </div>
        </div>
        {{else}}
                <li>No posts found.</li>
        {{/each}}
        {{else}}
                {{> spinner}}
        {{/if}}

</div>

**Comment by hellogerard** [comment]
I believe posts are already sorted by date (more recent first). Are they not for you?

**Comment by olumytee** [comment]
Indeed they are when I deployed to meteor.com but they weren't when I was working on localhost.
