### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by nolotus** [meteor-blog/meteor-blog#237]
3 months ago?

**Comment by hellogerard** [comment]
I've been working on it in spurts. 

Just this morning, I moved it to an org to [encourage more contribution](http://fabien.potencier.org/about-personal-github-accounts.html), and to allow for the "package" to be split into more modular components. 

If you are interested in helping, send me a message and I will add you to the org.

**Comment by idmontie** [comment]
:+1:
