### ISSUE TITLE
Semantic-UI fork

### ISSUE THREAD

**Issue by mikkhait** [meteor-blog/meteor-blog#238]
Guys, I've started work on porting admin to Semantic-UI. Feel free to contribute.

https://github.com/mikkhait/meteor-blog

**Comment by hellogerard** [comment]
That's awesome. How polished is it? Would you be interested in moving it into the [org](https://github.com/meteor-blog) as an official variant? Then you (or others) could contribute on it as members of the org.

Currently, there are questions of how to keep the two repos in sync. But it's makes for a good starting requirement for splitting the package into more modular components (e.g. `meteor-blog:core`, `meteor-blog:ui-bootstrap`, `meteor-blog:ui-semantic-ui`).

**Comment by mikkhait** [comment]
Hey @hellogerard, I suppose I should be checking my github notifications more often. To be honest I don't remember how polished what this commit as it was a long time ago. I would love to move it to the org, so other can contribute.
