### ISSUE TITLE
<p class="commentable-section" data-section-id="1"> being added to every post

### ISSUE THREAD

**Issue by olumytee** [meteor-blog/meteor-blog#243]
hello, I don't know what every post is wrapped in <p class="commentable-section" data-section-id="1"> </p> tags that are also displayed on the post page. The <p></p> tags also appear in the Mongo document for every post. Did I do something wrong ? 
example here https://theala.ga/blog/hello
Thanks

**Comment by hellogerard** [comment]
That markup is used by SideComments.js. Are you using SideComments by any chance?

```
Blog.config({
  comments: {
    useSideComments: true, // default is false
    allowAnonymous: true   // default is false
  }
});
```
