### ISSUE TITLE
Feature Request: Date format for European style dates

### ISSUE THREAD

**Issue by thoragio** [meteor-blog/meteor-blog#244]
Hi,

It would be great if there was a way in Blog.config({}) to set the date format to European style (8 Feb 2016) instead of the American style (Feb 8th, 2016).

I see the blogFormatDate attribute can be tweaked in the boot.coffee file, but I don't know enough to do this myself (yet!) and install the package on my own.

I tried writing my own Template helper, but that does not seem to work.

This in a .js file in the client directory:

`
Template.registerHelper("formatDate", function(date) {
  return moment(new Date(date)).format("MMM Do, YYYY");
});
`

And this in the .html file of the blog template, which I have made slight styling modifications to:

`
Posted on {{formatDate publishedAt}}
`

There is no date displayed. :-(

Sorry I can not be more proactive on this one (i.e., code a pull request) but I have only been learning to program now for about 3 months, so the learning curve is still a bit steep. Hope to be doing that in the not-too-distant future.

Thank you.

--Thor

**Comment by thoragio** [comment]
I've thought about this and have come up with this proposed solution:

lib/boot.coffee ->
Add a new parameter under Blog.config called dateFormat and set it to true.

client/boot.coffee ->
Add an if/else that sets the date format to American style if Blog.settings.dateFormat is true, or European (international really) if false

README.md ->
Update accordingly to highlight this new feature.

Then it is simply a matter of adding the appropriate flag in Blog.config({}) for the package user to toggle the date format.

If this is acceptable, let me know and I will create a pull request.

**Comment by hellogerard** [comment]
Rather than a flag, I think the config setting should be a date format string, passable to Moment.js. The default can be whatever the format is now, but configurable by the user. You will have to find all the places a date is displayed and modify them (but you would have to do that anyway). What do you think?

**Comment by thoragio** [comment]
OK, so the date format string could be the default "MMM Do, YYYY", "DD MMM YYYY", "YYYY-MMM-DD" or some variation like that. I like that because it gives more flexibility.

I'm not sure I understand your point about finding all the places the date is displayed and modifying them.  I thought I would just need to modify the template helper in client/boot.coffee.  It currently is:

`
Template.registerHelper "blogFormatDate", (date) ->
  moment(new Date(date)).format "MMM Do, YYYY"
`

So could it not just be changed to:

`
Template.registerHelper "blogFormatDate", (date) ->
  moment(new Date(date)).format Blog.settings.dateFormat
`

**Comment by hellogerard** [comment]
Oh, I suppose you're right. I hadn't looked at the code before commenting. If that's all there is, then that's all there is.

**Comment by thoragio** [comment]
Great! I've made the changes and initiated a pull request.

**Comment by hellogerard** [comment]
Closed by #246.
