### ISSUE TITLE
Uploaded Image half "greyed out"?

### ISSUE THREAD

**Issue by sanders4069** [meteor-blog/meteor-blog#247]
Any idea why when I upload an image half of it is 'greyed out'? I have uploaded many different pics to see why, can't figure it out. See example:  

![example](https://cloud.githubusercontent.com/assets/1220224/13057157/82e6a004-d3d7-11e5-92a2-fbd0d7307dcd.png)

**Comment by thoragio** [comment]
Are you uploading directly from your camera, or is the image stored on your computer?

How large are the image files?

**Comment by sanders4069** [comment]
Images from computer. I just did a file size comparison, uploaded 2 photos of completely different file sizes and a larger image (1.32MG) was greyed out, but the smaller one (300kb) rendered just fine.

Also, onclick functions dont work on the greyed out part. So is this a sizing issue? Can I modify the limit, or set parameters on users uploads so its clearer from the users point of view?

See new example:
![example](https://cloud.githubusercontent.com/assets/1220224/13060494/2465916c-d3ef-11e5-8b71-1dcc6c52ba5b.png)

**Comment by hellogerard** [comment]
Yeah, I see it too. If you inspect the element in the console, it is the image uploader's progress overlay. It's not getting completely removed for large images. Probably fix this with a CSS hack.
