### ISSUE TITLE
How to get the post _id?

### ISSUE THREAD

**Issue by kemelzaidan** [meteor-blog/meteor-blog#249]
Hi,

sorry if the question is stupid, but I'm just starting with Meteor. How should I get the _id of a post, if I have no need to create a `new Mongo.Collection` anywhere and all I have to do is setup a `Blog.config({})` function?

I need to pass the post _id to another template.

**Comment by hellogerard** [comment]
Can you show some example code?  If you have a `post` in context anywhere, then the field is just `_id`....

**Comment by kemelzaidan** [comment]
I want to use it with comments-ui package (https://atmospherejs.com/arkham/comments-ui) and as you can see below, you need to pass the id of the post:

```
<div class="comment-section">
    {{> commentsBox id=documentId}}
</div>
```

So, I have no idea on how to get it in order to pass to the comments-ui template.

**Comment by hellogerard** [comment]
Then you can try this:

```
<div class="comment-section">
    {{> commentsBox id=_id}}
</div>
```
