### ISSUE TITLE
Tags issue: Displaying previously entered tag

### ISSUE THREAD

**Issue by ignivaankushrishi** [meteor-blog/meteor-blog#259]
When I enter tag, then the last tag entered is displayed twice.
![screen shot 2016-04-01 at 11 32 07 am](https://cloud.githubusercontent.com/assets/16954229/14203475/d04ab9da-f81b-11e5-96ab-8d80dd544759.png)

the last entered tag is displayed in the textbox

**Comment by hellogerard** [comment]
I can't get reproduce this. How are you entering your tags (`Enter`, `Tab`, arrows, mouse)?

**Comment by sasikanth513** [comment]
@hellogerard  It happens with both tab and enter on focus leave of tags input

http://g.recordit.co/qyE93J5crJ.gif
