### ISSUE TITLE
Trouble with meteor 1.3

### ISSUE THREAD

**Issue by zhaoyao91** [meteor-blog/meteor-blog#260]
I can't import anything in this package. after seeking the code, I found it exports nothing at all, it just attach `Blog` as global variable. This is wrong with meteor 1.3.

it doesn't work with meteor 1.3, even after config the routing. console still prints 
```
There is no route for the path: /blog
```

**Comment by ArdentKid** [comment]
+1 Any ideas?

**Comment by deborah-ufw** [comment]
The iron router dependency is not documented in the meteor-blog install instructions. This user may need to add iron router to his meteor project with "meteor add iron:router".

**Comment by deborah-ufw** [comment]
+1.

I am having no success at getting either the blog package or the blog example project running.

**Comment by hellogerard** [comment]
@zhaoyao91 I have Meteor Blog working find with a couple apps on Meteor 1.3.1. What exactly are you seeing?

The `There is no route for the path /blog` error (if you are using Flow Router) was a pretty bad bug just fixed in 0.8.6. I just released it. Can you try again with the latest release?

**Comment by zhaoyao91** [comment]
thanks, I will have a try.
