### ISSUE TITLE
documentation - specify dependencies, supported meteor version, also fix link to blog example

### ISSUE THREAD

**Issue by deborah-ufw** [meteor-blog/meteor-blog#262]
Hello -

This package seems like a dream come true, but it looks like the documentation is leading users off into the wilderness.

1. The installation instructions are a little unclear. In my meteor project directory, the install script fails to do anything. If I clone it into my meteor project directory, then run the install script, there are many errors and meteor can't launch the app. 
2. It would be useful to have a "Dependencies" section in your main Readme, before the Installation instructions.
3. Iron:router is one of the package dependencies that must be installed, and is not documented.
4. Which versions of Meteor are supported? 
5. The example blog's url gets a DNS error at http://blog-example.meteor.com/

Hearts and smiles were floating in bubbles over my head when I saw this package, but there are just a ton of errors when I try to compile it out of the box. With problems in the documentation, a potentially unsupported Meteor version (1.3), and no working example, I'm experiencing new bubbles over my head with perplexed, anxious icons instead of hearts and smiles.

Thank you for your hard work. 
Deborah

**Comment by urco** [comment]
+1. I have tried to work with the package in a project the last weeks and finally I think that I will surrender :( . It looks like a great package but it seems is deprecated (or abandoned). The documentation how you say is not so good, and the issues and problems reported in Github repository are not reply....:( The issues section looks like death....
I hope that the creators find some free time to fix and improve this great package.

**Comment by deborah-ufw** [comment]
I surrendered also at 3:05 a.m.

**Comment by hellogerard** [comment]
I'm sorry for your troubles. I know it takes up time. Regarding your questions:

1. I'm not sure what you're saying. There are no real "installation" instructions other than adding the package. There are no real dependencies that you have to worry about (the package system takes care of these). Yes, either Iron Router or Flow Router is required, but there is a note about that in the README, and the app throws an error as well if it doesn't find one or the other. 
2. See above.
3. See above.
4. I hadn't tested Meteor Blog with Meteor 1.3.1 yet until just today, and it appears to be running find in my test app and in the (example blog app)[https://github.com/meteor-blog/example-blog-app). What are you seeing with 1.3.1?
5. Meteor no longer offers free hosting, where the example blog was running. I don't want to pay anything to host the example blog app :-) so it's offline for now. I added a note to the README. Apologies for any confusion there.

**Comment by deborah-ufw** [comment]
Hi!

Thank you very much for quick troubleshooting and response. The package looks awesome and I will try again. I definitely share your feelings about hosting - no worries :) 

Now that I've run around with Meteor for a few days, I understand that "meteor add package:name" requires nothing else, but as a beginner, when "meteor add ryw:blog"  made no changes to the directory and didn't create a visible blog (also, there was no visible error on the screen, but I didn't check the console), I started trying all kinds of other things. I will try again - the package looks awesome.

I didn't catch the flow router dependency in the Readme, also there is a kadira:blaze-template required that I didn't catch. A "Dependencies" section at the top really would help - the Readme is a long one and these seem a little buried in there. It seems like everything the user would need to get up and running in three steps up at the top would eliminate confusion and redundant issues.

With 1.3.1 when I submitted the issue, what I saw was no change in my default meteor app visible in the browser (the one created with meteor create), and no change in the app's file structure. Nothing at all happened. I wound up messing around for a long time, because I just started working with Meteor. 

Thank you so much for your hard work and quick response - I'm working through some Meteor tutorials today and hope before midnight that I can try your beautiful package again. It seems to be exactly what I'm looking for, and in exciting Meteor - what could be better???!!!  Nothing could be better.

:)

**Comment by hellogerard** [comment]
You're right about the dependencies. I updated the README!

**Comment by deborah-ufw** [comment]
Hi everyone!  I went through several Meteor tutorials and have got this up and running in Meteor 1.3.2 - it does work as intended and is fabulous!!!

Here's what I had to do that I didn't initially know about...
1. make an app - there must be an existing Meteor app for the blog to be hooked into (I made a bare bones 1-page app based on the Meteor "to-do's" tutorial to get started)
2. add the dependencies - 1)Kadira flow router 2)Kadira blaze layout 3)accounts-ui
3. specify what kind of authentication you want in your command line in the main app directory (I used "meteor add accounts-password")
4. put the login button snippet somewhere on your app's html page "{{> loginButons}}"
5. use the command line to  "meteor add ryw:blog"
6. go to your login page and login
7. go to your-app/admin/blog

...now you can start populating your blog. Cheers!
