### ISSUE TITLE
Multiple authors

### ISSUE THREAD

**Issue by ryw** [meteor-blog/meteor-blog#71]
Was thinking it might be cool to allow multiple authors to be listed on a blog post, just as a book can have multiple authors. Haven't really seen this on other blogs before, but something I could see doing on the Differential blog or my personal site (I plan to move it to meteor-blog soon).

Thoughts?

**Comment by semikolon** [comment]
+1

**Comment by apaleja** [comment]
+1

**Comment by dannyk08** [comment]
+1

**Comment by urco** [comment]
+1

**Comment by franckfeusseu** [comment]
+1
